### ISSUE TITLE
Dataset Documentation for the Multivariate Dataset (Input_Data.xlsx)

### ISSUE THREAD

**Issue by wjcapehart** [iliasmachairas/Tutorials_twd#1]
Dear Ilias. 

Could you include the original source for the water use dataset?  I want to be able to use it in one of our numerical methods introductory classes.  I'm looking to shake things up - my old one is a concrete compression test dataset and this one is a good digestible example.  To do so, however, crediting the data source (along with you, of course) would be needed. 

Much Obliged & Best Regards
Bill Capehart
South Dakota Mines, Civil & Envir Engineering

**Comment by iliasmachairas** [comment]
Dear Bill Capehart,

Apologies for my late reply. Data comes from a town in North Greece. 
Hope it helps!

Let me know if you want more information.

Regards,
Ilias Machairas
